import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Script from "next/script";
import { GoogleTagManager } from "@next/third-parties/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="/main.js"
          // src="https://newcookiebucket.s3.us-east-2.amazonaws.com/cookie_consent_11/363cc9bc-7ee8-43de-bd64-4238ee416ba2/main_4f8046e.js"
          id="lb-cookie-consent"
          strategy="beforeInteractive"
        ></Script>
        <Script
          src={"./injectCookies.js"}
          type="text/javascript"
          strategy="beforeInteractive"
        />
        <GoogleTagManager gtmId="GTM-5GXBGFPT" />
        <Script src="https://test-cookies.tiiny.site/show_alert.js" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
